# Generated by Django 5.0.3 on 2025-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
