# Generated by Django 5.0.3 on 2025-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_groceryitem_options_alter_grocerylist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
